#!/usr/bin/perl

use strict;
use warnings;
use lib './lib';
use Ipso;
use Getopt::Long::Descriptive;

my ($opt,$usage)=describe_options("%c  %o",
	['Parameters:'],
		['block|b=s' => 'Add an IPv4 or IPv6 network block.'   ,{required=>1}],
		['note|n=s'  => 'Some descriptive text for the block.' ,{required=>1}],
		['help'      => 'Print help and usage.'],
	[],
	['Examples:'],
		["$0 -b 192.168.0.0/16 -n 'Some RFC1918 space.'"],
		["$0 --block dead:beef::/64 --note 'An IPv6 block.'"],
	[],
);

print($usage->text), exit if $opt->help;
my $newblock=$opt->block;
my $note=$opt->note;
chomp($newblock);
$newblock=~s/\s+//g;

unless (is_ipv4_cidr($newblock) || is_ipv6_cidr($newblock)){
	print "Error: Invalid network block.\n";
	exit;
}

addIPBlock($newblock,$note);
