#!/usr/bin/perl

use strict;
use warnings;
use lib './lib';
use Ipso;
use Text::ASCIITable;
use Data::Dumper;

my $block=$ARGV[0];
my ($ipblock,%allocs)=getAllocationInfo($block);
my $family=4;
if (is_ipv6_cidr($ipblock)){
	$family=6;
}
my $table = Text::ASCIITable->new({ headingText => "Allocations in IPv$family Block $ipblock" });
$table->setCols('Alloc ID','Range','IP count','Used (%)','Free (%)','Notes');
foreach my $thisalloc (sort keys %allocs){
	my $firstip=$allocs{$thisalloc}{firstip};
	my $lastip=$allocs{$thisalloc}{lastip};
	my $ipcount=$allocs{$thisalloc}{ipcount};
	my $used=$allocs{$thisalloc}{used};
	my $note=$allocs{$thisalloc}{note};
	my $free=$ipcount-$used;
	my $usedpcent='0';
	if ($used!=0){
		$usedpcent=sprintf("%.3g",$used/$ipcount*100);
	}
	my $freepcent=sprintf("%.3g",100-$usedpcent);
	$table->addRow($thisalloc,"$firstip - $lastip",$ipcount,"$used ($usedpcent%)","$free ($freepcent%)",$note);
}
print $table;
