#!/usr/bin/perl

use strict;
use warnings;
use lib './lib';
use Ipso;
use Text::ASCIITable;
use Data::Dumper;
use Getopt::Long::Descriptive;

my ($opt,$usage)=describe_options("%c  %o",
	['Parameters:'],
		['block|b=s' => 'Specify IP CIDR range or IP block ID to list.', {required=>1}],
		['help'      => 'Print help and usage.'],
	[],
	['Examples:'],
		["$0 -b 192.168.0.0/16"],
		["$0 --block 3"],
	[],
);

print($usage->text), exit if $opt->help;

my $block=$opt->block;
my ($ipblock,%allocs)=getAllocationInfo($block);
my $family=4;
if (is_ipv6_cidr($ipblock)){
	$family=6;
}
my $table = Text::ASCIITable->new({ headingText => "Allocations in IPv$family Block $ipblock" });
$table->setCols('Alloc ID','Range','IP count','Used (%)','Free (%)','Notes');
foreach my $thisalloc (sort keys %allocs){
	my $firstip=$allocs{$thisalloc}{firstip};
	my $lastip=$allocs{$thisalloc}{lastip};
	my $ipcount=$allocs{$thisalloc}{ipcount};
	my $used=$allocs{$thisalloc}{used};
	my $note=$allocs{$thisalloc}{note};
	my $free=$ipcount-$used;
	my $usedpcent='0';
	if ($used!=0){
		$usedpcent=sprintf("%.3g",$used/$ipcount*100);
	}
	my $freepcent=sprintf("%.3g",100-$usedpcent);
	$table->addRow($thisalloc,"$firstip - $lastip",$ipcount,"$used ($usedpcent%)","$free ($freepcent%)",$note);
}
print $table;
